### ISSUE TITLE
8.0.5.41 IBM Java SDK for MACOSX?

### ISSUE THREAD

**Issue by heapey** [IBM/spm-kubernetes#11]
https://ibm.github.io/spm-kubernetes/01-prereq/3rdparty-sw states to install 8.0.5.41 IBM Java SDK - however following the link there is no version for Mac? Thanks

**Comment by andreyzher** [comment]
Mac isn't an officially supported platform for SPM development and/or deployment. The middleware part of the setup must be performed on Linux or Windows.
The Kubernetes/Docker part of the setup can be done on any of the platforms supporting installation of Docker/Minikube.

**Comment by mikyjpeg** [comment]
Since there is no recent update to the ticket I'm going to close it. Feel free to reopen.
