### ISSUE TITLE
CE Ingress controller Rules created when the Application isn't deployed

### ISSUE THREAD

**Issue by meathead23** [IBM/spm-kubernetes#14]
**Describe the bug**
In SPM Umbrella chart under `helm-charts/spm/values.yaml` when ceApp has the following values set:

```
  ceApp:
    enabled: false
    replicaCount: 1
    imageLibrary: ''
    imageName: ce-ihs
    imageTag: latest
    ingressPath: /universal/*
    resources: {}
```

The helm charts still produce the ingress controller rules, this causes the ingress controller provisioning to fail. this is due to this if statement in `helm-charts/spm/templates/ingress.yaml`:

```
          {{- if .Values.global.ceApp.imageTag }}
          - path: {{ .Values.global.ceApp.ingressPath | default "/universal" }}
            backend:
              serviceName: {{ $.Release.Name }}-ce-app
              servicePort: http
          {{- end }}
```

shouldn't this be set to?:

```
          {{- if .Values.global.ceApp.enabled }}
          - path: {{ .Values.global.ceApp.ingressPath | default "/universal" }}
            backend:
              serviceName: {{ $.Release.Name }}-ce-app
              servicePort: http
          {{- end }}
```

**To Reproduce**
1. Edit helm with the ceApp section attached above
2. Run helm install
3.  Check ingress controller config which should include. the following rule:

```
            {
              "path": "/universal",
              "backend": {
                "serviceName": "spm-dev01-ce-app",
                "servicePort": "http"
              }
```

Since that service is not installed:

```
[matt.smithson@ssvc-c-403 dashboard]$ kubectl get service
NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                         AGE
spm-dev01-apps-curam       ClusterIP   172.20.35.250    <none>        8443/TCP                        5h1m
spm-dev01-apps-rest        ClusterIP   172.20.103.175   <none>        8443/TCP                        5h1m
spm-dev01-ihs              NodePort    172.20.120.160   <none>        8443:31010/TCP                  5h1m
spm-dev01-mqserver-curam   NodePort    172.20.254.199   <none>        9443:30411/TCP,1414:31859/TCP   137m
spm-dev01-mqserver-rest    NodePort    172.20.247.88    <none>        9443:30562/TCP,1414:32102/TCP   137m
spm-dev01-xmlserver        ClusterIP   172.20.16.199    <none>        1800/TCP                        5h1m
```

ingress controller setup fails.

**Expected behavior**
Helm charts should not produce ingress rules for components that aren't enabled.

**Screenshots**
See logs above

**Please complete the following information:**
    * OS: AWS EKS 1.14
    * Docker Version:  Docker version 18.09.5, build e8ff056
    * Minikube Version: N/a
    * Ant Version: 1.10.6
    * Java Version: Java 8 (version packaged with Liberty) 
    * Liberty  Version: 19.0.0.12-full-java8-ibmjava
    * Cúram SPM Version: 7.0.10

**Log Collection**

See above.

**Comment by niambhscullion12** [comment]
Thanks so much for raising the issue @meathead23 . 
Much appreciated. 
Niambh
