### ISSUE TITLE
Broken Link in Prerequisites

### ISSUE THREAD

**Issue by bresnahr** [IBM/spm-kubernetes#18]
On [https://ibm.github.io/spm-kubernetes/01-prereq/Docker-Kubernetes-Helm/](https://ibm.github.io/spm-kubernetes/01-prereq/Docker-Kubernetes-Helm/), in the section about Kubernetes and Minikube the **next page** link is broken.
The url is takes you to is [https://ibm.github.io/spm-kubernetes/01-prereq/Docker-Kubernetes-Helm/minikube](https://ibm.github.io/spm-kubernetes/01-prereq/Docker-Kubernetes-Helm/minikube)

**Comment by dobharweim** [comment]
Hi @bresnahr, thanks for highlighting this, the correct link is https://ibm.github.io/spm-kubernetes/01-prereq/minikube. We will have it corrected in the live artefact soon.

**Comment by niambhscullion12** [comment]
Thanks @dobharweim - much appreciated
