### ISSUE TITLE
db2 dependency in spm/requirements.yaml

### ISSUE THREAD

**Issue by meathead23** [IBM/spm-kubernetes#23]
Describe the bug
In SPM Umbrella chart under helm-charts/spm/requirements.yaml there is a dependency on db2 as follows:

```
- name: db2
  version: "~1.3.0"
  repository: "@local-development"

```

There is no valid charts for this dependency and therefore it  should be removed as it causes the following issue when packaging the spm umbrella chart.

```
Error: db2 chart not found in repo http://chartmuseum.apps-crc.testing
```

**Comment by niambhs** [comment]
Thanks Matt

**Comment by niambhs** [comment]
Thanks Matt.

**Comment by mikyjpeg** [comment]
That's correct. The dependency shouldn't be there, as stated in the runbook a remote database should be used to interact with the helm deployment. This was part of an internal spike that was incorrectly released.
