### ISSUE TITLE
internal.docker.repository causes building of CE and StaticContent Dockerfiles to fail

### ISSUE THREAD

**Issue by meathead23** [IBM/spm-kubernetes#25]
**Issue:**

In the Dockerfiles for CE and StaticContent the FROM statement In both files is currently set to:

```
ARG DOCKER_REGISTRY="internal.docker.repository"

#Final
FROM ${DOCKER_REGISTRY}/ubi7/ibm-http-server:${HTTP_VERSION}
```

this repository can't be resolved and is inconsistent with the Liberty, batch and MQ docker files. 

**Solution:**

This should be reverted back to:

`FROM ibmcom/ibm-http-server:${HTTP_VERSION}`

**Comment by andreyzher** [comment]
Actually it's a gap in the documentation currently.

`ibmcom/ibm-http-server` images are Ubuntu based, and the requirement is to use UBI-based images.

For IHS, it's a case of build-your-own-base until https://github.com/WASdev/ci.docker.ibm-http-server/pull/44 is merged and UBI images for IHS are published.

**Comment by meathead23** [comment]
@andreyzher OK I see, but wouldn't the WAS, MQ images exact also need to be built on UBI?

**Comment by andreyzher** [comment]
Those are already published as UBI images - I'm working with the publishers of the IHS image to get rid of the pre-build requirement.

**Comment by meathead23** [comment]
OK Cool, well if you want to close this and link it there then by all means.

**Comment by andreyzher** [comment]
I'll keep this open until we update either the documentation or the Dockerfiles, whichever comes first in time for the next drop.
