### ISSUE TITLE
CuramBirtViewer chart still causes frequent logout's

### ISSUE THREAD

**Issue by meathead23** [IBM/spm-kubernetes#33]
Issue:

When building the CuramBirtViewer image like so:

```yaml
# Building curambirtviewer image
cd "${SPM_CONTAINERISATION_HOME}/dockerfiles/Liberty/"
docker build \
     --tag curambirtviewer:latest \
     --file ClientEAR.Dockerfile \
     --build-arg "SERVERCODE_IMAGE=servercode:latest" \
     --build-arg "EAR_NAME=CuramBIRTViewer" .
```

On deployment if this container using the SPM helm charts, SPM constantly logs out the logged in user, this was an issue in https://github.com/OpenLiberty/open-liberty/issues/9663 which has now been fixed in Liberty version `20.0.0.6` which seems to be used to build the container images, however the logout's still occur.

**Comment by andreyzher** [comment]
The issue you're referencing only provides the API, but the CuramLoginModule in SPM 7.0.10.0 does not make use of this, as the API was not available in time for the 7.0.10 GA release.

Regardless of Liberty version, SPM 7.0.10.0 must still be deployed with OpenLDAP to handle the sessions correctly.

**Comment by IanScottIBM** [comment]
Hi. I thought OpenLDAP was going to be removed as a dependency. Is this not the case anymore?

**Comment by mikyjpeg** [comment]
Hi Ian, yes that's the plan. But together with Liberty 20.0.0.6, it requires also a new SPM version.

**Comment by IanScottIBM** [comment]
Hi. That is what we thought, a combination of both updated WAS Liberty and change to SPM. Any idea when a version that doesn't require OpenLDAP may be required?

**Comment by niambhscullion12** [comment]
Hi @IanScottIBM , that temporary dependance on OpenLDAP will be in place when we have upgraded to support Liberty 20.0.0.6. 

N..

**Comment by mikyjpeg** [comment]
I'm closing it as it is working as expected, with the current version of SPM, as for previous comments
