### ISSUE TITLE
Failed to pull image at Helm install step

### ISSUE THREAD

**Issue by heapey** [IBM/spm-kubernetes#43]
Prereqs all followed (i believe)
Images built and pushed to Docker Registry ok
Helm charts prepared, packaged and pushed ok.

Now run:
helm install release2 local-development/spm -f ../static/resources/crc-values.yaml

in separate tab:
 kubectl get pods -w
NAME                                     READY   STATUS             RESTARTS   AGE
release1-apps-apply-customsql-mbl2f      0/1     ImagePullBackOff   0          18m
release2-apps-apply-customsql-fc8pb      0/1     ImagePullBackOff   0          53s
releasename-apps-apply-customsql-2bm8l   0/1     ImagePullBackOff   0          22m
release2-apps-apply-customsql-fc8pb      0/1     ErrImagePull       0          56s

(note releasename and release1 were also earlier fails)

Viewing log:
 kubectl logs -f pod/release1-apps-apply-customsql-mbl2f
Error from server (BadRequest): container "apply-customsql" in pod "release1-apps-apply-customsql-mbl2f" is waiting to start: trying and failing to pull image

OS = MacOSx Catalina 10.15.7
ChartMuseum installed locally and run like this:
chartmuseum --debug --port=8080   --storage="local"   --storage-local-rootdir="./chartstorage"

CRC installed locally:
crc version
CodeReady Containers version: 1.15.0+e317bed
OpenShift version: 4.5.7 (embedded in binary)

Docker version 19.03.12

**Comment by andreyzher** [comment]
@heapey 

Please check the image being pulled by any of the failing pods using the `oc describe pod` command.

If you are using CRC's internal image registry, there are several points to check:

* Make sure that the target project exists before pushing the images
  * Verify the images were correctly published using `curl -k -ukubeadmin:$(oc whoami -t) https://default-route-openshift-image-registry.apps-crc.testing/v2/_catalog` and examine the output for your images
* Push images using the "public" registry hostname (`default-route-openshift-image-registry.apps-crc.testing`), and set the "private" hostname (`image-registry.openshift-image-registry.svc:5000`) in the Helm override values file
* Check that the details in the override values file correspond to the actual location where the images were published (i.e. `global.images.registry` and `global.images.imageLibrary` reflect the location where the images were pushed)

The sample file (`crc-values.yaml`) you are referencing expects the Docker images to have been published as `default-route-openshift-image-registry.apps-crc.testing/ocp/<batch>:latest` to a project named `ocp`

**Comment by heapey** [comment]
thanks for the pointer, i think there were two things:
1) I had to set imageLibrary: 'spm-deploy' in crc-values.yamp  (not ocp. Note spm-deploy was from earlier steps in the runbook (update runbook with more detail?)
2) this still failed, tracked it down to duplicate 'data:' element in mq-secret.yaml (is this a known issue?)

Tried new helm deployment (had to kill previous attempts by killing jobs that were resurrecting failed attempts) 

But now get:
Failed to pull image "image-registry.openshift-image-registry.svc:5000/spm-deploy/batch:latest": rpc error: code = Unknown desc = unable to retrieve auth token: invalid username/password: unauthorized: authentication required

Obviously missed another step somewhere, will go back and look at this tomorrow but just wanted to give an update. Thanks for the pointer that got me further though

**Comment by andreyzher** [comment]
Thanks for the update.

I'll go over the text in the morning - the instructions assume that the namespace (project) where you push the images is the same as where you are deploying the application, though it is possible to separate this by allowing the Service Accounts in the deployment namespace to access the Registry namespace.

```
oc policy add-role-to-group \
    system:image-puller \
    system:serviceaccounts:<destination_project> \
    -n <source_project>
```

This allows `<destination_project>` to pull images from `<source_project>`.

I'll check what's going on with the duplicate key in the `mq-secret.yaml` file - that had been fixed back in August on our development branch, so it's strange that it isn't hasn't been picked up by our publish mechanism.

**Comment by heapey** [comment]
Thanks.
I believe my project where i'm pushing and deploying is the same, namely 'spm-deploy'.

I tried the above command but still get same error:
Failed to pull image "image-registry.openshift-image-registry.svc:5000/spm-deploy/batch:latest": rpc error: code = Unknown desc = unable to retrieve auth token: invalid username/password: unauthorized: authentication required

Attaching my crc-values.yaml - you can see i have set my imagePullSecret with kubeadmin and password, is this correct?


Note I also tried the command suggested on https://ibm.github.io/spm-kubernetes/prereq/openshift/codeready-containers:
oc adm policy add-scc-to-user spm-dev-scc -z system:serviceaccount:${releasename}:default, but this fails:

The ClusterRoleBinding "system:openshift:scc:spm-dev-scc" is invalid: subjects[0].name: Invalid value: "system:serviceaccount:spm-deploy:default": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

Looking at this more, is $releasename correct (set to spm-deploy earlier?) Later on in the helm install, running the install command will create a service account with the same name as the release given in the command:
e.g. helm install release11 local-development/spm -f ../static/resources/crc-values.yaml  then followed by:
kubectl get serviceaccounts
NAME                              SECRETS   AGE
builder                           2         41h
default                           2         41h
deployer                          2         41h
release11-apps-secret-manager     2         6m26s

Regardless, I tried running both the oc adm policy add-scc-to-user and the helm install using releasename ='spm-deploy', but got same errors.

What is spm-dev-scc in more detail? I looked in the source and see createSCC.sh, and now not sure if the build should take care of this step, or it is needed in the pre-reqs section as described in the link above.

FYI if i do oc get scc i get:
NAME               PRIV    CAPS         SELINUX     RUNASUSER          FSGROUP     SUPGROUP    PRIORITY     READONLYROOTFS   VOLUMES
anyuid             false   <no value>   MustRunAs   RunAsAny           RunAsAny    RunAsAny    10           false            [configMap downwardAPI emptyDir persistentVolumeClaim projected secret]
hostaccess         false   <no value>   MustRunAs   MustRunAsRange     MustRunAs   RunAsAny    <no value>   false            [configMap downwardAPI emptyDir hostPath persistentVolumeClaim projected secret]
hostmount-anyuid   false   <no value>   MustRunAs   RunAsAny           RunAsAny    RunAsAny    <no value>   false            [configMap downwardAPI emptyDir hostPath nfs persistentVolumeClaim projected secret]
hostnetwork        false   <no value>   MustRunAs   MustRunAsRange     MustRunAs   MustRunAs   <no value>   false            [configMap downwardAPI emptyDir persistentVolumeClaim projected secret]
node-exporter      true    <no value>   RunAsAny    RunAsAny           RunAsAny    RunAsAny    <no value>   false            [*]
nonroot            false   <no value>   MustRunAs   MustRunAsNonRoot   RunAsAny    RunAsAny    <no value>   false            [configMap downwardAPI emptyDir persistentVolumeClaim projected secret]
privileged         true    [*]          RunAsAny    RunAsAny           RunAsAny    RunAsAny    <no value>   false            [*]
restricted         false   <no value>   MustRunAs   MustRunAsRange     MustRunAs   RunAsAny    <no value>   false            [configMap downwardAPI emptyDir persistentVolumeClaim projected secret]

i.e. spm-dev-scc is not included.

This feels like potentially deep water so will hold fire for now, but please let me know if any other logs or info would help the diagnosis, or even if i should start again....
many thanks
[crc-values.yaml.txt](https://github.com/IBM/spm-kubernetes/files/5450765/crc-values.yaml.txt)

**Comment by mikyjpeg** [comment]
The `mq-secret.yaml` error has been fixed in a new drop of the runbook we released today. See PR above.

**Comment by andreyzher** [comment]
Thanks for pointing out some stale docs - `spm-dev-scc` is actually no longer required, since all components in the latest version of the runbook are designed to run under the `restricted` policy.

While I rebuild my own CRC environment to deploy with your attached version of `crc-values.yaml`, try removing the `global.imagePullSecret` key - the token generated for the default Service Account should already have permissions to pull the images, so injecting `kubeadmin` credentials shouldn't be needed

**Comment by heapey** [comment]
Thanks! I think my original config was the default:
  imagePullSecret:
    registry: *imageRegistry
    username: kubeadmin
    password:

You are suggesting remove the whole thing?

Note I moved to try minikube as i couldn't get past the above error. Just got minkube up and running so will be spending a bit more time poking around there for a bit first and then go back to try the above suggestion on CRC if thats ok, so will let you know, thanks again

**Comment by andreyzher** [comment]
Hi @heapey 

I checked locally that removing the `imagePullSecret` section from the CRC values file works correctly (something we'll fix in November's runbook release)

![image](https://user-images.githubusercontent.com/2170339/97882757-dfbd9c00-1d1b-11eb-8856-6152dde2c877.png)

> Actually, since my minikube docker images are stored in the minikube docker registry, and crc ones in the crc registry, given that the helm charts prepared as per https://ibm.github.io/spm-kubernetes/deployment/hc_preparation are platform agnostic, and the only thing that differentiates minikube vs crc is on the helm install step, specifying the override values yml, then in theory if i try the helm install on the CRC version again it should have no impact on the minikube version? Does that make sense, or anything else I need to consider?

Indeed, if you have pushed the images into both, then you can freely switch between Minikube and CRC. The only thing you have to change about your values file is the ingress hostname and the registry address - both use built-in credentials for pulling the images from the internal registry that don't need to be explicitly specified. In terms of the `helm` commands - the process is identical.

**Comment by heapey** [comment]
Hi, 
Got to try this again and can confirm that completely removing the imagePullSecret now gets the process further and 3 out of 5 pods complete creating and up and running:
 kubectl get pods
NAME                                           READY   STATUS    RESTARTS   AGE
crcrel1-apps-curam-consumer-78665dcdcc-ssh2l   0/1     Pending   0          14m
crcrel1-apps-curam-producer-5cbf6f78b-wwsl2       0/1     Pending   0          14m
crcrel1-mqserver-curam-775c99dd46-c9mxn           1/1     Running   0          14m
crcrel1-web-68bbdb447d-jlhrs                                    1/1     Running   0          14m
crcrel1-xmlserver-6ccb95b7df-mb5w5                       1/1     Running   0          14m 

Unfortunately I'm out of CPU on my local laptop:
kubectl describe pods crcrel1-apps-curam-consumer-78665dcdcc-ssh2l

gives:

Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  71s (x12 over 14m)  default-scheduler  0/1 nodes are available: 1 Insufficient cpu, 1 Insufficient memory.

Happy to close this issue, as I know the CRC system requirements are a separate thing, but in case you need to update docs for clarity, in summary 2 things were needed in this issue :
- remove the imagePullSecret from crc-values.yml
- set  imageLibrary: 'spm-deploy' in crc-values.yaml (to match the value that is set in https://ibm.github.io/spm-kubernetes/prereq/openshift/codeready-containers)

Also on similar topic of updating docs, it would be good to distinguish between $releasename set in the prereqs, and the 'releasename' mentioned in https://ibm.github.io/spm-kubernetes/deployment/hc_deployment - since from what i can tell they can be independent, so slightly confusing to the first time user.

Many thanks for your help in getting me this far

**Comment by andreyzher** [comment]
Glad to hear you were unblocked on the original issue. Unfortunately between CRC's own requirements and the resource requirements for SPM, there is not a lot of room to reduce the system footprint to comfortably fit on a developer Macbook issued in the last ~2 years.

I'm going to keep this open until we push out the documentation updates.
