### ISSUE TITLE
Can't access Curam after helm deployment

### ISSUE THREAD

**Issue by heapey** [IBM/spm-kubernetes#46]
Looking at https://www.ibm.com/support/knowledgecenter/SS8S5A_7.0.11/com.ibm.curam.wlp.doc/Deployment_WLP/cWLPTestingDeployment.html it says to get the URL for the deployed app to search for CWWKT0016I.
For me this gives:
[AUDIT   ] CWWKT0016I: Web application available (default_host): https://rel6-apps-curam-producer-88b8cc888-rml4q:8443/Curam/

This fails to return anything.

I also tried using the IP given from 'minikube ip', i.e. https://192.168.99.104:8443/Curam/, but this gives a 403:
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/Curam/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}

I tried  kubectl describe service rel6-web and  kubectl describe service rel6-apps-curam to see if there was an Ingress IP as suggested by some googling, but that didn't yield anything

attached output of kubectl logs for web, producer and consumer. 

I can see in the consumer some issue with curamtimerdb  (possibly missed a WLS config step) but wouldn't have thought this would cause the basic access issue? Any thoughts on what to do next much appreciated.

(also dockered onto the actual consumer/producer to see if anything in logs but the kubectl version seemed to have better info, unless i was looking in wrong place on WLS)

thanks
[consumer.log](https://github.com/IBM/spm-kubernetes/files/5466393/consumer.log)
[producer.log](https://github.com/IBM/spm-kubernetes/files/5466394/producer.log)
[web.log](https://github.com/IBM/spm-kubernetes/files/5466395/web.log)

**Comment by meathead23** [comment]
@heapey I think this is an issue/feature of the ingress controller, I believe you've set the ingress controller to allow a hostname for SPM like `minikube.local` the ingress controller uses the Host header sent by the client to identify where the calls going. 

So your IP address is an invalid host and the ingress controller rejects the request.

if you run this:

```
sudo -c "echo $(minikube ip) minikube.local >> /etc/hosts"
```

That should add an entry to your hosts file allowing you to access the cluster from your laptop via minikube.local  and the ingress controller should access the request.

**Comment by andreyzher** [comment]
The steps in KC documentation are only applicable to a development environment on a VM.

The URL for accessing the application in Kubernetes would have been printed at the end of the `helm install` output.
Was an Ingress resource created? Check using `kubectl get ingress`.
As @meathead23 mentioned, for a Minikube environment based on the samples in the runbook, this would be `minikube.local`, so the URL would be `https://minikube.local/Curam`

Regarding the database error, we would need some more information:

* Are the database name (`global.database.dbName`) and hostname (`global.database.hostname`) set correctly?
* Is the database populated with the SPM data (ie have the `database prepare.application.data` targets been run against it)
* Does the database have SSL enabled, and are the appropriate values set in the Helm override values?
* Are the database credentials passed using override values or a pre-existing secret, and are the passwords correctly encoded?

**Comment by heapey** [comment]
DB issue gone, may have been docker container issue.

Checked /etc/hosts with @meathead23 and found some spurious characters , removed those and now https://minikube.local/Curam is accessible, however now get:
503 Service Temporarily Unavailable

copied output of a few commands below, also logs from each pod - can't see any errors, any clues?? 
Many thanks

**kubectl get ingress**
NAME   CLASS    HOSTS            ADDRESS          PORTS     AGE
rel5   <none>   minikube.local   192.168.99.104   80, 443   5d3h
rel6   <none>   minikube.local   192.168.99.104   80, 443   5d3h

**kubectl describe ingress rel6**
Name:             rel6
Namespace:        default
Address:          192.168.99.104
Default backend:  default-http-backend:80 (<none>)
TLS:
  rel6-tls terminates minikube.local
Rules:
  Host            Path  Backends
  ----            ----  --------
  minikube.local  
                  /Curam         rel6-apps-curam:https (172.17.0.6:8443)
                  /CuramStatic   rel6-web:https (172.17.0.7:8443)
Annotations:
  meta.helm.sh/release-namespace:                   default
  nginx.ingress.kubernetes.io/affinity:             cookie
  nginx.ingress.kubernetes.io/backend-protocol:     HTTPS
  nginx.ingress.kubernetes.io/proxy-read-timeout:   150
  nginx.ingress.kubernetes.io/session-cookie-path:  /
  ingress.bluemix.net/ssl-services:                 ssl-service=rel6-apps-curam;ssl-service=rel6-web;
  ingress.bluemix.net/sticky-cookie-services:       serviceName=rel6-apps-curam name=curamRoute hash=sha1 path=/;serviceName=rel6-web name=webRoute hash=sha1 path=/;
  meta.helm.sh/release-name:                        rel6
Events:                                             <none>

**kubectl get pods** 
^[[BNAME                                        READY   STATUS             RESTARTS   AGE
rel6-apps-curam-consumer-5d6b5b4cff-v2ch8   1/1     Running            2          4d22h
rel6-apps-curam-producer-88b8cc888-rml4q    1/1     Running            4          4d22h
rel6-batch-queued-1604080800-5sd28          0/1     Completed          0          4d2h
rel6-mqserver-curam-548796f5bb-7q4fv        1/1     Running            3          4d22h
rel6-web-84fcc8598b-qmvw2                   1/1     Running            2          4d22h
rel6-xmlserver-86b68d75d6-77vgk             0/1     ImagePullBackOff   1          5d3h

[rel6-apps-curam-consumer-5d6b5b4cff-v2ch8.log](https://github.com/IBM/spm-kubernetes/files/5483926/rel6-apps-curam-consumer-5d6b5b4cff-v2ch8.log)
[rel6-web-84fcc8598b-qmvw2.log](https://github.com/IBM/spm-kubernetes/files/5483927/rel6-web-84fcc8598b-qmvw2.log)
[rel6-mqserver-curam-548796f5bb-7q4fv.log](https://github.com/IBM/spm-kubernetes/files/5483928/rel6-mqserver-curam-548796f5bb-7q4fv.log)
[rel6-apps-curam-producer-88b8cc888-rml4q.log](https://github.com/IBM/spm-kubernetes/files/5483929/rel6-apps-curam-producer-88b8cc888-rml4q.log)

**Comment by heapey** [comment]
from above note there are 2 ingress, one from rel6 (the desired one) and an old attempt rel5. 
helm list indicated that rel5 deployment was still there in some shape, even though i thought i had deleted the rel5 pods.
@meathead23 suggested to 'helm delete rel5', this then properly cleared the earlier failed attempt.
this was the final piece of the puzzle and now able to login successfully :-)
Thanks both for your help
