### ISSUE TITLE
What is the need for SPM JMS Engine in SPM OpenShift Reference Architecture

### ISSUE THREAD

**Issue by sraman100** [IBM/spm-kubernetes#50]
Can you clarify what is the need for SPM JMS Engine (On Virtual Machine) in SPM Open Shift Reference Architecture?

**Comment by mhcastro** [comment]
For SPM running on OpenShift, IBM MQ Queue Managers can be hosted on OpenShift as Statefulset pods or on virtual machines. 

1. If the preference is to run IBM MQ Queue Managers as Statefulset pods on OpenShift, the IBM MQ Certified Containers needs to be used.
2. If the preference is to run IBM MQ Queuer Managers on virtual machines, the IBM MQ LTS needs to be used.

More information on the IBM MQ release types can be found [in this link](https://www.ibm.com/support/knowledgecenter/SSFKSJ_9.2.0/com.ibm.mq.pla.doc/q004715_.htm).

**Comment by mikyjpeg** [comment]
I'm closing this for now, as explained by Marcelo the reference picture is illustrating both possibilities. If you have any additional comments feel free to post them here.

**Comment by sraman100** [comment]
Thanks for the quick response.
