### ISSUE TITLE
Please clarify Open Shift CRC installation documentation in the SPM Runbook 

### ISSUE THREAD

**Issue by kdombros** [IBM/spm-kubernetes#53]
I am following the SPM Runbook and I want to install Openshift CRC (please see  https://ibm.github.io/spm-kubernetes/prereq/openshift/codeready-containers).  I clicked that that _latest release_ link to download Code Ready Containers, but the page catches me off guard. I was expecting to see the software listed/download options. Instead I had to poke around a bit, and I finally realized/discovered what I needed was under the "Sandbox" tab. We should update the documentation to clarify that / eliminate confusion for the developer/customer. 

It looks like this when you click _latest release_ link: 
<img width="1539" alt="image" src="https://user-images.githubusercontent.com/15349348/106019487-b5684a00-6090-11eb-9e3f-59a3f66bae02.png">

The installer and pull secret are actually under the Sandbox tab: 

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/15349348/106019600-d335af00-6090-11eb-9a84-7221d2f69078.png">

**Comment by andreyzher** [comment]
Hi @kdombros 

Thanks for pointing this out. This is certainly not what the page looked like when we write that section.

**Comment by andreyzher** [comment]
Looks like the RedHat site has been updated and the link currently in the runbook is once again redirecting to the intended Sandbox/Local page.
Closing.
