### ISSUE TITLE
NetworkManager issues when configuring CRC 

### ISSUE THREAD

**Issue by kdombros** [IBM/spm-kubernetes#56]
I'm following the instructions to install CodeReady Containers (https://ibm.github.io/spm-kubernetes/prereq/openshift/codeready-containers/#creating-a-crc-project).  I'm using an RHEL VM, and when I attempt the "crc start" command I get the following error regarding NetworkManager: 

```
[vnc@bluffing1 ~]$ crc start
INFO Checking if running as non-root              
INFO Checking if podman remote executable is cached 
INFO Checking if admin-helper executable is cached 
INFO Checking minimum RAM requirements            
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if libvirt daemon is running        
INFO Checking if a supported libvirt version is installed 
INFO Checking if crc-driver-libvirt is installed  
INFO Checking if systemd-networkd is running      
INFO Checking if NetworkManager is installed      
INFO Checking if NetworkManager service is running 
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists 
File not found: /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf: stat /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf: no such file or directory
```

Can someone advise how _/etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf_ file should be configured? 

There is some info [here](https://access.redhat.com/documentation/en-us/red_hat_codeready_containers/1.0/html/getting_started_guide/troubleshooting-codeready-containers_gsg) but I assume that is just an example? Not sure what values I should put

**Comment by kdombros** [comment]
For the record, I tried both the values shown from the RedHat Troubleshooting page as well as my own IP address, but in either case I get **_File has unexpected content: /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf_** error. 

It looks like this: 
```
server=/crc.testing/192.168.130.11
server=/apps-crc.testing/192.168.130.11
```

**Comment by andreyzher** [comment]
@kdombros Did you run `crc setup`? That command was supposed to configure the missing NetworkManager files.

**Comment by kdombros** [comment]
I did run that command - but now I think I understand what went wrong:  after that step, I discovered the NetworkManager was _**disabled**_, so I think the set up was incomplete. I did a `crc delete` and recreated and now that problem is fixed. That's the Good news! 

Now the bad news: I'm getting this error from `crc start`: 
`Error creating machine: Error creating the VM: Error creating machine: Error in driver during machine creation: host is not running: getting ip during machine start`

LMK if you can offer advise on how to figure out what is wrong... I'll take a Google of it now

**Comment by andreyzher** [comment]
Just a hunch, but could you run `lscpu` and check the Vendor ID and search the flags at the bottom of the output for `vmx`.
Only the hosts with Intel CPUs in that environment have support for nested virtualisation enabled.

If your VM is running on one of the AMD nodes, you will have to reprovision in SVL.
If you'd like a shortcut, one of the other teams published an [Ansible playbook](https://github.com/IBM/community-automation/tree/master/ansible/request-crc-fyre-play) that will do the whole setup for you, although with an older version of CRC (according to the ReadMe).

**Comment by kdombros** [comment]
Yea I always provision at SVL so looks like I'm good on that hunch: 

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             4
NUMA node(s):          1
Vendor ID:             **`GenuineIntel`**
CPU family:            6
Model:                 61
Model name:            Intel Core Processor (Broadwell, IBRS)
Stepping:              2
CPU MHz:               2300.000
BogoMIPS:              4600.00
Virtualization:        VT-x
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl eagerfpu pni pclmulqdq **`vmx`** ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f rdseed adx smap avx512cd xsaveopt arat md_clear spec_ctrl

**Comment by andreyzher** [comment]
This looks like the same error as reported in https://github.com/code-ready/crc/issues/1213
Running CRC in a VM is not officially supported, though in that case upgrading to a later version of RHEL helped.

**Comment by kdombros** [comment]
Hey Andrey - I think you determined the Hypervisor on my RHEL VM is based on Ubuntu?  So one way or another I'm trying to  use CRC on an unsupported platform right? We should close this issue off / I'll re-visit CRC on a cleaner VM, etc.

**Comment by andreyzher** [comment]
Indeed - the issue here appears to be an older hypervisor, which is not something that we can control.
I provisioned 4 new VMs (RHEL 7.8/7.9/8.3, and Ubuntu 20.04) on the same platform and was able to setup CRC in all cases, with the core difference being newer hosts.

Closing.
