### ISSUE TITLE
Potential documentation update

### ISSUE THREAD

**Issue by echeungGitHub** [IBM/spm-kubernetes#59]
During going through the SPM Runbook (https://ibm.github.io/spm-kubernetes/prereq/kubernetes/minikube), I have found that some commands seem to be outdated or incorrect.

For example, in "minikube start --vm-driver=virtualbox --cpus 4 --memory 8G --insecure-registry "192.168.0.0/16" --disk-size='30G' --kubernetes-version v1.18.6",  --vm-driver='': DEPRECATED, use `driver` instead and no need to have '' for disk-size...etc. 

If I am correct, we might need to update the document? Thanks.

* Minikube version is v1.17.1 and docker is 20.10.2

**Comment by niambhscullion12** [comment]
Thanks Ed.
