### ISSUE TITLE
helm commands not working

### ISSUE THREAD

**Issue by VarunKoteshwar** [IBM/spm-kubernetes#6]
The following commands are not working, note I am on helm 3.

helm push apps local-development

Error: unknown command "push" for "helm"
Did you mean this?
pull
Run 'helm --help' for usage.

**Comment by andreyzher** [comment]
This requires the [Helm Push](https://github.com/chartmuseum/helm-push) plugin to be installed - a prerequisite that had been overlooked.

It is possible to work without the Helm Push plugin by packaging the Helm charts manually and placing them in the storage location of ChartMuseum, but it makes for a more awkward developer experience.

**Comment by VarunKoteshwar** [comment]
Thank you, these links were broken and hence all these. 

The last step is failing: 
 helm install curamrelease local-development/spm

Error: found in Chart.yaml, but missing in charts/ directory: apps, batch, ce-app, configmaps, ihs, mqserver, openldap, xmlserver

**Comment by andreyzher** [comment]
Please double-check that you ran all the commands in the [Preparing Helm charts](https://ibm.github.io/spm-kubernetes/03-deployment/hc_preparation#packaging-the-helm-charts) section.

Before you can install/push the `spm` chart, all the other charts need to be `helm push`'ed to `local-development`, then the dependencies of the chart need to be resolved using `helm dependency update spm` (or `helm dep up spm` for short)

You can verify whether the necessary charts actually made it to ChartMuseum by running `curl http://127.0.0.1:8080/index.yaml` - this will return the list of indexed charts in YAML format.

With the dependencies resolved, you should be in position to run `helm push spm local-development`

Finally, you will need to refresh the chart index by running `helm repo update`.

**Comment by VarunKoteshwar** [comment]
I performed all these. Here is the snippet from above url.

spm:
  - apiVersion: v1
    created: "2020-03-27T01:49:23.888365Z"
    description: Umbrella Helm Chart for Full Curam Deployment of SPM within a Kubernetes
      Cluster
    digest: 61d97212ce1219429cfa83642bec3a492b381eb4b309ea67759220ea62827475
    home: https://www.ibm.com/watson-health/solutions/social-program-management
    icon: https://avatars2.githubusercontent.com/u/1459110
    keywords:
    - Liberty
    - Minikube
    - IKS
    - Curam
    - SPM
    maintainers:
    - name: Cúram SPM Dev Team
      url: https://github.com/IBM/spm-kubernetes
    name: spm
    sources:
    - https://github.com/IBM/spm-kubernetes
    urls:
    - charts/spm-1.2.0.tgz
    version: 1.2.0


----------
I am not able to find the location charts/spm-1.2.0.tgz
