### ISSUE TITLE
Helm labelling improvements - Service Mesh

### ISSUE THREAD

**Issue by tidridgej** [IBM/spm-kubernetes#61]
Have been going through setting up SPM with OpenShift service mesh. I came across a few inconsistences with the naming of ports and pod labels which caused some problems getting this set up

1. Naming of ports following: [protocol-suffix](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/)
For example, MQ server has: 
      `name: console-https`
To show metrics in Kiali the expected is:
 `name: https-console`

2. Adding in the labels for pods app and version to the helm charts, as this is what is displayed on the graph charts, rather than a user having to go through and add them in individually.
Labels to add: `name` and `version` for each deployment

**Comment by andreyzher** [comment]
Hi @tidridgej 

Thanks for raising this.

Our labels are based on the [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) for Kubernetes, but if it makes it easier to use a Service Mesh I see no harm in adding a few extra labels.
The labels we provide are just a starting point, and you are free to customise them to best suit your environment.

Regarding the port names, again, no harm in renaming to suit the service mesh requirements.

We will include both requests in an upcoming release.

**Comment by andreyzher** [comment]
The new labels have been delivered in our [April release](https://github.com/IBM/spm-kubernetes/releases/tag/21.4.0).
