### ISSUE TITLE
Producer and consumer pods fail to stabilize initially

### ISSUE THREAD

**Issue by micsafi** [IBM/spm-kubernetes#64]
Following symptoms appear on minikube cluster v1.15.1:

When the SPM Helm chart in installed and the different deployments are created on k8s, the SPM producer and consumer pods fail to start initially and only after few rounds of re-attempts the stabilize to running state. On the failed start attempts, following type of errors can be observed on Pod Events:

`MountVolume.SetUp failed for volume "ejb-bindings" : failed to sync configmap cache: timed out waiting for the condition`

Same error is repeated for all volumes required by the pod.

![image](https://user-images.githubusercontent.com/32633455/111142874-d7108880-858d-11eb-8573-1f521316f806.png)

**Comment by andreyzher** [comment]
Hi @micsafi 

Did this happen after restarting Minikube / your host, and is it still happening?

This can happen in "low-availability" environments (e.g. Minikube) when the Kube API Server is not ready to talk to the Kubelet (either it's still starting itself or lacks resources to respond in a timely manner) when the pods are attempting to start.

The option is to either redeploy the release, or force the pods to be recreated by deleting them:

```
kubectl delete pod -l release=releaseName
```

This command would delete all pods for the Helm release "releaseName", but the respective replication controllers will create new pods.

**Comment by micsafi** [comment]
@andreyzher , Thanks for the reply. 

This issue occured also after restarting the minikube (and the fusion VM that hosts it). 

Since the problem fixes itself after some time, I think we can close the issue. I will re-open if more persistent errors start to occur.

**Comment by andreyzher** [comment]
Thanks for confirming that the pods do stabilise after a period of time.
