### ISSUE TITLE
Hitting Docker Resource Limit when trying to create ChartMuseum Container

### ISSUE THREAD

**Issue by kdombros** [IBM/spm-kubernetes#66]
I have registered with Docker Hub and authenticated, but I'm still seeing the resource limit error when I follow the steps to create the Chart Museum Docker container (as described [here](https://ibm.github.io/spm-kubernetes/prereq/chartmuseum) in the Runbook).  

Is there any workaround - such as what is described for [MiniKube](https://ibm.github.io/spm-kubernetes/prereq/kubernetes/minikube#docker-hub-download-rate-limit-and-minikube)? 

LMK - thanks!

**Comment by andreyzher** [comment]
Hi @kdombros 

Could you please post the exact commands you've executed and the resulting logs? 
If you had logged in previously, I suggest trying to run `docker logout` before attempting to login.

Thanks

**Comment by andreyzher** [comment]
I see you're using `/usr/bin/docker-current` - would this happen to be Docker version 1.13.x?
If so, that is unsupported (not just by SPM for this purpose, but also by Docker Inc.) - you will need to upgrade to the latest version.

**Comment by kdombros** [comment]
whoops - yes it was version 1.13.1. I have now upgraded: 

```
docker --version
Docker version 20.10.6, build 370c289
```
I hoped that would fix the error too, but no such luck. This is happening on a Fyre VM if that matters at all.

**Comment by kdombros** [comment]
Ok @andreyzher  looks like this is not a surprise on Fyre: https://ibm-cloud.slack.com/archives/C09EJRGHH/p1603970144160700

I discovered I have Chartmuseum image on a local VM, so I pushed it to my CSP artifactory repository, and then pulled it from there to fire it up :-) 

**Push:** 
* `docker login -u w3id -p artifactoryToken` _wh-ghhs-csp-team-common-docker-local.artifactory.swg-devops.com_
* `docker tag chartmuseum/chartmuseum:v0.12.0` _wh-ghhs-csp-team-common-docker-local.artifactory.swg-devops.com/chartmuseum/chartmuseum:v0.12.0_
* `docker push` _wh-ghhs-csp-team-common-docker-local.artifactory.swg-devops.com/chartmuseum/chartmuseum:v0.12.0_ 

**Pull/Run:** 
* `docker login -u w3id -p artifactoryToken` _wh-ghhs-csp-team-common-docker-local.artifactory.swg-devops.com_
* `docker pull`  _wh-ghhs-csp-team-common-docker-local.artifactory.swg-devops.com/chartmuseum/chartmuseum:v0.12.0_ 
*  docker run --rm -d --name chartmuseum \
  -p 8080:8080 \
  -e DEBUG=true \
  -e STORAGE=local \
  -e STORAGE_LOCAL_ROOTDIR=/tmp/charts \
  chartmuseum/chartmuseum:v0.12.0


Close it up!

**Comment by andreyzher** [comment]
Glad you were able to sort it out!

In case you ever need to provision registry your own outside of our internal infrastructure, take a look at these 2 open source projects:

- [Docker Registry](https://docs.docker.com/registry/)
- [Harbor](https://goharbor.io/)

Closing.

**Comment by kdombros** [comment]
The easier solution was to just register/login to Docker Hub: https://hub.docker.com. Then from the command line issue: 
`docker login -u username`
