### ISSUE TITLE
ChartMuseum links broken

### ISSUE THREAD

**Issue by VarunKoteshwar** [IBM/spm-kubernetes#7]
Link to chartmuseum is not working.

https://ibm.github.io/spm-kubernetes/03-deployment/hc_preparation/

**Comment by mikyjpeg** [comment]
The link should point to https://ibm.github.io/spm-kubernetes/01-prereq/chartmuseum

**Comment by VarunKoteshwar** [comment]
Thank you, this link worked.

**Comment by mikyjpeg** [comment]
I will leave it open, until fixed.
