### ISSUE TITLE
Producer and Consumer pods aren't starting - "Insufficient CPU" warning message

### ISSUE THREAD

**Issue by kdombros** [IBM/spm-kubernetes#70]
After a successful helm install/deployment, the application is not accessible. The "Producer" and "Consumer" pods are in a Pending state, and examining their logs they are stating insufficient CPU.  We are using Fyre VM's that have 4 CPU's and 32Gb of memory. See attached for logs - please advise. Thanks! 

[producer consumer logs.zip](https://github.com/IBM/spm-kubernetes/files/6368307/producer.consumer.logs.zip)

**Comment by podgek** [comment]
We also tried overriding the chart values related to requested CPUs. The override seemed to get applied, but same problem.

**Comment by ourboy** [comment]
Hi @kdombros 

can you confirm the value set for `crc config set cpus <whole-number>`?

What are you setting the cpu override value to be?

reviewing the logs for both the producer and consumer, it seems that you do not have enough cpu's available on the VM
`  Warning  FailedScheduling  81s (x58 over 42m)  default-scheduler  0/1 nodes are available: 1 Insufficient cpu.`

Can you increase the CPU's on the VM from 4 to 8, then increase the crc config cpus value to 4 or 6. 

Can you rerun and confirm if you are seeing the same issue?

**Comment by kdombros** [comment]
Sure thing @ourboy - this "experiment" was happening on @podgek's VM, so I'll wait for him to come on line (West Coast) and we'll take a poke at it. We will report back - thanks!

**Comment by podgek** [comment]
"crc config set cpus" is 4.

"What are you setting the cpu override value to be?": where is this done? If done in the overrides file, then the request number is now set to 2 and the limit is set to 2. The default values for these settings were 1 and 1.5.

Right now I am trying to reinstall and have run into some other environmental issue. Not sure what is going on; something dumb probably. I need to get over that issue before I can get back on track with the CPU issue. Will work with Kev to compare both of our environments.

**Comment by podgek** [comment]
OK, I got past my environmental issues. Ran "crc config set cpus 6", and the server eventually started up ok. Strangely though, the Fyre virtual machine only has 4 CPUs available to it. Any idea what sort of CPU the command "crc config set cpus 6" is referring to?
