### ISSUE TITLE
ESDC HFP - Technical Exception Encountered in IBM MQ with OpenShift Containerized Environment

### ISSUE THREAD

**Issue by surkramu** [IBM/spm-kubernetes#73]
We are supporting ESDC's High Fidelity Prototype Project which is aimed to demonstrate Curam in OpenShift Containairized environment. Our SI is following the runbook provided by PD to build and deploy the Curam application. The following technical exception is encountered for a simple Universal Access application being submitted and further processed by the REST Consumer. This is kind of blocking the High Fidelity Prototype project which has huge implications in restoring Customer confidence in using Curam for longer term in upcoming ESDC projects.

Support Case **WH00012069** is also raised to track this issue.
https://ibmwatsonhealth.force.com/mysupport/s/case/5001U00000lEOFZQA4/esdc-hfp-technical-exception-encountered-in-ibm-mq-with-openshift-containerized-environment?openCase=true

[INFO ] FFDC1015I: An FFDC Incident has been created: "javax.transaction.xa.XAException: The method 'xa_start' has failed with errorCode '-6'. com.ibm.tx.jta.impl.JTAXAResourceImpl.start 307" at ffdc_21.04.28_20.53.01.0.log
[INFO ] FFDC1015I: An FFDC Incident has been created: "javax.transaction.xa.XAException: The method 'xa_start' has failed with errorCode '-6'. com.ibm.tx.jta.impl.RegisteredResources.startRes 1053" at ffdc_21.04.28_20.53.01.1.log
[ERROR ] WTRN0078E: An attempt by the transaction manager to call start on a transactional resource has resulted in an error. The error code was XAER_PROTO. The exception stack trace follows: javax.transaction.xa.XAException: The method 'xa_start' has failed with errorCode '-6'.
at com.ibm.mq.jmqi.JmqiXAResource.start(JmqiXAResource.java:980)
at com.ibm.mq.connector.xa.XARWrapper.start(XARWrapper.java:680)
at com.ibm.ws.Transaction.JTA.JTAResourceBase.start(JTAResourceBase.java:121)
at [internal classes]
at com.ibm.mq.connector.inbound.AbstractWorkImpl.run(AbstractWorkImpl.java:210)
at com.ibm.ws.jca.inbound.security.JCASecurityContextService.runInInboundSecurityContext(JCASecurityContextService.java:49)
at [internal classes]
[INFO ] FFDC1015I: An FFDC Incident has been created: "javax.transaction.SystemException: XAResource start association error:XAER_PROTO com.ibm.tx.jta.impl.RegisteredResources.enlistResource 523" at ffdc_21.04.28_20.53.01.2.log
[INFO ] FFDC1015I: An FFDC Incident has been created: "javax.transaction.SystemException: XAResource start association error:XAER_PROTO com.ibm.tx.jta.TransactionImpl.enlistResource 2042" at ffdc_21.04.28_20.53.01.3.log
[INFO ] FFDC1015I: An FFDC Incident has been created: "javax.transaction.SystemException: XAResource start association error:XAER_PROTO com.ibm.ws.ejbcontainer.mdb.MessageEndpointBase.beforeDelivery 1244" at ffdc_21.04.28_20.53.01.4.log
[INFO ] Message delivery to an MDB 'curam.util.jms.MDBProxyDPEnactmentMDB_49ac78a4@99d46d8f(BeanId(CuramServerCode#coreinf-ejb.jar#DPEnactmentMDB, null))' failed with exception: 'beforeDelivery failure'.
[INFO ] FFDC1015I: An FFDC Incident has been created: "com.ibm.websphere.csi.CSITransactionRolledbackException: Transaction marked rollbackonly com.ibm.ejs.container.EJSContainer.postInvoke 2326" at ffdc_21.04.28_20.53.01.5.log
[INFO ] FFDC1015I: An FFDC Incident has been created: "javax.ejb.TransactionRolledbackLocalException: ; nested exception is: com.ibm.websphere.csi.CSITransactionRolledbackException: Transaction marked rollbackonly com.ibm.ws.ejbcontainer.mdb.MessageEndpointBase.afterDelivery 1280" at ffdc_21.04.28_20.53.01.6.log
[INFO ] WTRN0006W: Transaction 000001791A41120D00000001681E949CCC38DCA6F5D43D42714F62BDC24547D1E7EFE6F5000001791A41120D00000001681E949CCC38DCA6F5D43D42714F62BDC24547D1E7EFE6F500000001 has timed out after 180 seconds.
[INFO ] WTRN0124I: When the timeout occurred the thread with which the transaction is, or was most recently, associated was Thread[Default Executor-thread-6,5,Default Executor Thread Group]. The stack trace of this thread when the timeout occurred was:
java.lang.Object.wait(Native Method)
java.lang.Object.wait(Object.java:218)
com.ibm.ws.threading.internal.BoundedBuffer.waitGet_(BoundedBuffer.java:176)
com.ibm.ws.threading.internal.BoundedBuffer.take(BoundedBuffer.java:647)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1085)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java.lang.Thread.run(Thread.java:822)

And here is what the MQ does:

2021-04-28T20:53:01.444Z AMQ6125E: An internal IBM MQ error has occurred.
2021-04-28T20:53:01.444Z AMQ6184W: An internal IBM MQ error has occurred on queue manager QM1.

**Comment by VarunKoteshwar** [comment]
the version of MQ certified container you are using? 9.1.5
method of MQ deployment (stateful set or operator or standalone) Operator Enabled
the version of MQ Adaptor you are using? 
the version of Liberty?
what customization (if any) have been done? None
how many occurrences of the issue are encountering? This issue occurs when JMS messages are fired. The above steps(Submitting an application), invokes JMS messages
Replica counts of the Rest Producer and Consumer.
what release version of the SPM-Kubernetes are you currently using?

Additional Info:
MQ storage class is specified as Azure storage

The issue is reproducible for any use cases that invoke JMS message.

**Comment by mhcastro** [comment]
Small correction: 

```
method of MQ deployment (stateful set or operator or standalone) standalone deployment / replicaset
```

**Comment by ourboy** [comment]
IBM MQ XAER_PROTO issue has been observed in the JMS Consumer pods when JMS transactions is processed by a newly deployed pod, at the initial JMS transactions. An interim release has been created to clarify as a known issue.
