### ISSUE TITLE
Could not allocate resources as specified

### ISSUE THREAD

**Issue by VarunKoteshwar** [IBM/spm-kubernetes#8]
I use Mac, and not able to allocate 4 cpus and 8 GB RAM. Do we really need that much to run Curam?. The following downgraded configuration worked. As per the instructions, I always get a timeout.

minikube start --vm-driver=vmware --cpus 2 --memory 4G --insecure-registry "192.168.3.0/16" --disk-size='20G' --kubernetes-version v1.16.7

**Comment by andreyzher** [comment]
Were you also able to launch SPM inside the reduced Minikube VM?

Between the Minikube services themselves, and a deployed SPM application (Curam EAR only - no Rest, Citizen Portal, or other applications) even 8GB is quite tight, when you consider the SPM [development environment](https://www.ibm.com/support/pages/node/300175) requirements.

I would recommend closing down any other memory intensive applications (e.g. Eclipse).

Regarding the timeout - could you be a little more specific please (the full error message would help).

**Comment by VarunKoteshwar** [comment]
I was able to create and reallocate. The other issue I faced was the name of the Minikube, I had to change as the IP address got freezed. Using a different Minikube helped.
