### ISSUE TITLE
Docker execution fails

### ISSUE THREAD

**Issue by VarunKoteshwar** [IBM/spm-kubernetes#9]
I am trying to download WebSphere Liberty image, and execute the following:

https://ibm.github.io/spm-kubernetes/02-build-images/setup_docker_context
docker run --rm \
    -v $ANT_HOME:/tmp/ant \
    -v $SPM_HOME/dockerfiles/Liberty/content/release-stage:/work/dir \
    -v $SPM_HOME/dockerfiles/Liberty/content/release-stage/SetEnvironment.sh:/work/SetEnvironment.sh \
    -w /work/dir \
    -u root \
    -e ANT_HOME=/tmp/ant \
    -e WLP_HOME=/opt/ibm/wlp \
    websphere-liberty:19.0.0.12-full-java8-ibmjava \
    bash -c 'export PATH=$ANT_HOME/bin:$PATH:.; build.sh internal.update.crypto.jar'

There are couple of issues:
1. I get image not found, however, I was able to pull first
docker pull websphere-liberty:19.0.0.12-full-java8-ibmjava

then run the above.

2. While running I get the following error:
 docker run --rm \
    -v $ANT_HOME:/tmp/ant \
    -v $SPM_HOME/dockerfiles/Liberty/content/release-stage:/work/dir \
    -v $SPM_HOME/dockerfiles/Liberty/content/release-stage/SetEnvironment.sh:/work/SetEnvironment.sh \
    -w /work/dir \
    -u root \
    -e ANT_HOME=/tmp/ant \
    -e WLP_HOME=/opt/ibm/wlp \
    websphere-liberty:19.0.0.12-full-java8-ibmjava \
    bash -c 'export PATH=$ANT_HOME/bin:$PATH:.; build.sh internal.update.crypto.jar'
**Unable to locate tools.jar. Expected to find it in /opt/ibm/java/lib/tools.jar**

> Underlying reason is that /opt/ibm/java/lib folder is missing

**Comment by andreyzher** [comment]
Has `$SPM_HOME/dockerfiles/Liberty/content/release-stage/build/CryptoConfig.jar` been generated?

That message is coming from Ant itself because the base `websphere-liberty` image only contains a JRE, rather than a full JDK, so any compilation functions wouldn't work, but in this case they are not required either.

Here is the full expected output:

```
Unable to locate tools.jar. Expected to find it in /opt/ibm/java/lib/tools.jar
Buildfile: /work/dir/build.xml
Trying to override old definition of datatype string

internal.update.crypto.jar:
     [copy] Copying 1 file to /work/dir/project/properties
      [jar] Building jar: /work/dir/build/CryptoConfig.jar
     [copy] Copying 1 file to /opt/ibm/java/jre/jre/lib/ext

BUILD SUCCESSFUL
Total time: 1 second
```

**Comment by VarunKoteshwar** [comment]
$SPM_HOME/dockerfiles/Liberty/content/release-stage/build/CryptoConfig.jar is generated. However in the docker image, /opt/ibm/java/lib folder is missing, where the tools.jar should have been there.

**Comment by andreyzher** [comment]
It is not required in the context of this Ant target. That message coming from Ant itself, and it is acceptable in this scenario.

**Comment by VarunKoteshwar** [comment]
I have ignored this and moved on.
