### ISSUE TITLE
spm-21.9.0 kubeVersion incompatible with Kubernetes version

### ISSUE THREAD

**Issue by podgek** [IBM/spm-kubernetes#94]
Hi we just pulled the latest from github onto a machine that had an earlier version in place. Now getting this error when we try to do a helm install:

install.go:190: [debug] CHART PATH: /home/vnc/.cache/helm/repository/spm-21.9.0.tgz

Error: chart requires kubeVersion: >=1.19 which is incompatible with Kubernetes v1.22.0-rc.0+894a78b
helm.go:81: [debug] chart requires kubeVersion: >=1.19 which is incompatible with Kubernetes v1.22.0-rc.0+894a78b

does something need to be updated in the machine configuration?

Here is the helm install command we are running:
helm install release1 local-development/spm -f ~/Downloads/crc-values.yaml --timeout "15m0s"   --debug

**Comment by ourboy** [comment]
@podgek i am going to reopen this one for tracking purposes. the charts in this repo do require a fix

**Comment by ourboy** [comment]
Closing.  updated as part of V8.0.1 December release
