### ISSUE TITLE
How do I stop and start openshift?

### ISSUE THREAD

**Issue by podgek** [IBM/spm-kubernetes#97]
Is there a way to stop and start the openshift like we did with WebSphere/Weblogic?
We have to set the referer properties so that the user can log in. As we cannot login we cannot trigger a reload of the caches. Only thing we can think of is to uninstall and reinstall but that seems like overkill.

**Comment by NiallWard** [comment]
Could you elaborate on what exactly you're trying to do, maybe referencing how you'd approach it on WebSphere?

If you're just looking to restart pods:

**Comment by podgek** [comment]
Thanks... I am trying to force a refresh of the in-memory caches.
So to do that do I only need to restart all the consumer and producer pods?

**Comment by NiallWard** [comment]
Probably include a restart of the http ones for completeness
